name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: poetry install

      - name: Lint
        run: make lint

      - name: Type Check
        run: make type-check

      - name: Run Tests
        run: make test

      - name: Security Check
        run: make security-check

      - name: Tag Release
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          VERSION=$(poetry version -s)
          git tag "v$VERSION"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/gopikrishna4595/gk6.git "v$VERSION"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        continue-on-error: false

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-
